import {Hero} from '../components/Hero';
import {Discography} from '../components/Discography';
import {MediaWall} from '../components/MediaWall';
import {StudioBooking} from '../components/StudioBooking';
import {SocialFeed} from '../components/SocialFeed';
import {ContactForm} from '../components/ContactForm';
import {Footer} from '../components/Footer';

const pillars=[['01','ARTIST DEVELOPMENT','From first voice memo to a finished identity, building records around the artist instead of forcing every artist into the same template.'],['02','PRODUCTION','Modern pop, electronic movement, live instruments and detailed arrangements designed to feel alive after the first listen.'],['03','VOCALS','Performance coaching, comping, editing and vocal production focused on character, emotion and clarity.'],['04','SONGWRITING','Hooks, toplines and lyrics developed collaboratively until the song has something real to say.']];
const process=['DISCOVER','WRITE','BUILD','RECORD','REFINE','RELEASE'];

export default function Page(){return <main className="overflow-hidden"><nav className="fixed top-0 z-40 flex w-full items-center justify-between border-b border-white/5 bg-[#0b0c0d]/80 px-5 py-5 backdrop-blur-xl md:px-12"><a href="#top" className="text-xs font-black tracking-[.22em]">ROSENFELD<span className="ml-2 font-normal text-white/35">PRODUCTIONS</span></a><div className="hidden gap-5 text-[10px] tracking-[.18em] text-mist md:flex"><a href="#catalog">MUSIC</a><a href="#profile">PROFILE</a><a href="#services">SERVICES</a><a href="#social">SOCIAL</a><a href="#booking">BOOK</a><a href="#contact" className="rounded-full border border-[#d7ff4f]/40 px-4 py-2 text-acid">CONTACT</a></div></nav><div id="top"><Hero/></div>

<section className="border-y border-white/10 bg-[#101112] px-6 py-10 md:px-12"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 text-center md:grid-cols-4"><div><b className="text-3xl font-black">20+</b><p className="mt-1 text-[9px] tracking-[.18em] text-mist">RELEASES & PROJECTS</p></div><div><b className="text-3xl font-black">3</b><p className="mt-1 text-[9px] tracking-[.18em] text-mist">CORE DISCIPLINES</p></div><div><b className="text-3xl font-black">∞</b><p className="mt-1 text-[9px] tracking-[.18em] text-mist">IDEAS IN PROGRESS</p></div><div><b className="text-3xl font-black">NJ</b><p className="mt-1 text-[9px] tracking-[.18em] text-mist">BASED · WORKING REMOTELY</p></div></div></section>

<Discography/>

<section id="profile" className="border-y border-white/10 bg-[#e8e3da] px-6 py-28 text-[#171816] md:px-12"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[.75fr_1.5fr]"><div><p className="text-xs font-black tracking-[.3em] text-[#625d54]">THE SONIC PROFILE</p><div className="mt-8 h-px w-full bg-black/15"/><p className="mt-6 max-w-xs text-sm leading-7 text-black/55">Rosenfeld Productions sits between the immediacy of a songwriter&apos;s room and the precision of modern production.</p></div><div><h2 className="max-w-4xl text-5xl font-black leading-[.88] tracking-[-.06em] md:text-8xl">BUILT FOR THE MOMENT<br/><span className="font-serif font-normal italic">after you press play.</span></h2><p className="mt-9 max-w-2xl text-lg leading-8 text-black/65">Moshe Rosenfeld is a singer, songwriter and producer creating emotionally direct music with pop instinct and electronic energy. The approach is simple: protect what makes an artist different, then make it hit harder.</p><div className="mt-12 grid gap-8 border-t border-black/15 pt-8 md:grid-cols-3"><div><b className="text-xs tracking-[.16em]">DIGITAL DETAIL</b><p className="mt-3 text-sm leading-6 text-black/55">Logic Pro workflows, synthesis, programmed drums and modern vocal editing.</p></div><div><b className="text-xs tracking-[.16em]">HUMAN PERFORMANCE</b><p className="mt-3 text-sm leading-6 text-black/55">Vocals, piano, guitar and arrangements that keep the imperfections worth hearing.</p></div><div><b className="text-xs tracking-[.16em]">RELEASE THINKING</b><p className="mt-3 text-sm leading-6 text-black/55">Records considered as songs, visuals, live moments and stories—not isolated files.</p></div></div></div></div></section>

<section id="services" className="mx-auto max-w-7xl px-6 py-28 md:px-12"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs tracking-[.35em] text-acid">WHAT HAPPENS HERE</p><h2 className="mt-5 text-6xl font-black tracking-[-.07em] md:text-8xl">MORE THAN<br/>A SESSION.</h2></div><p className="max-w-sm text-sm leading-7 text-mist">A flexible creative setup for artists who need one collaborator or a full production partner.</p></div><div className="mt-14 grid border-l border-t border-white/10 md:grid-cols-2">{pillars.map(([n,title,text])=><article key={n} className="group border-b border-r border-white/10 p-8 transition hover:bg-white/[.035] md:p-10"><div className="flex items-start justify-between"><span className="text-[10px] text-acid">{n}</span><span className="text-white/20 transition group-hover:text-acid">↗</span></div><h3 className="mt-16 text-3xl font-black tracking-[-.04em]">{title}</h3><p className="mt-4 max-w-md text-sm leading-7 text-mist">{text}</p></article>)}</div></section>

<section className="border-y border-white/10 bg-[#12110f] px-6 py-20 md:px-12"><div className="mx-auto max-w-7xl"><p className="text-xs tracking-[.35em] text-[#d9bca7]">THE PROCESS</p><div className="mt-10 grid gap-0 border-l border-t border-white/10 sm:grid-cols-2 lg:grid-cols-6">{process.map((step,i)=><div key={step} className="border-b border-r border-white/10 p-5"><span className="text-[10px] text-white/30">0{i+1}</span><p className="mt-8 text-xs font-black tracking-[.14em]">{step}</p></div>)}</div></div></section>

<SocialFeed/><MediaWall/>

<section className="mx-auto max-w-7xl px-6 py-28 md:px-12"><p className="text-xs tracking-[.35em] text-acid">SELECT A DIRECTION</p><div className="mt-8 grid gap-4 md:grid-cols-3"><a href="#booking" className="group min-h-72 border border-white/10 p-8 hover:bg-[#171914]"><span className="text-[10px] text-mist">01</span><h3 className="mt-24 text-4xl font-black">START A RECORD.</h3><p className="mt-4 text-sm text-mist">Production, writing and vocals from idea to release-ready master.</p></a><a href="#booking" className="group min-h-72 border border-white/10 bg-[#d7ff4f] p-8 text-black"><span className="text-[10px] text-black/50">02</span><h3 className="mt-24 text-4xl font-black">BOOK THE ROOM.</h3><p className="mt-4 text-sm text-black/60">Bring the song. Build the session around what it needs.</p></a><a href="#contact" className="group min-h-72 border border-white/10 p-8 hover:bg-[#201713]"><span className="text-[10px] text-mist">03</span><h3 className="mt-24 text-4xl font-black">TALK BUSINESS.</h3><p className="mt-4 text-sm text-mist">Features, collaborations, sync opportunities and creative partnerships.</p></a></div></section>

<StudioBooking/><ContactForm/><Footer/></main>}